# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TD9WKHNQLLEpAJg0u1x46IKCLpTI2TUS
"""

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])
if (x1==x2 and y1==y2 )or checkerboard[x2][y2]==1:
  print("No")
elif x2==x1+1 and y1==y2:
  print("Yes")
else:
  print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])
dx=abs(x1-x2)
dy=abs(y1-y2)
if (x1==x2 and y1==y2 )or checkerboard[x2][y2]==1:
  print("No")
elif(dx==2 and dy==1) or (dx==1 and dy==2):
  print("Yes")
else:
  print("No")

position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])
if (x1==x2 and y1==y2 )or checkerboard[x2][y2]==1:
  print("No")
elif abs(x1-x2)<=1 and abs(y1-y2)<=1:
  print("Yes")
else:
  print("No")



position1=input().split()
position2=input().split()
x1,y1=int(position1[0]),int(position1[1])
x2,y2=int(position2[0]),int(position2[1])
if checkerboard[x2][y2]==1:
  print("No")
elif (x1==x2 and y1==y2) or (abs(x1-x2)!= abs(y1-y2) and x1!= x2 and y1!= y2):
  print("No")
else:
  dx=(x2-x1)//max (1,abs(x2-x1))
  dy=(y2-y1)//max (1,abs(y2-y1))
  cx,cy=x1+dx,y1+dy
  reachable = True
  while cx!=x2 or cy!=y2:
    if checkerboard[cx][cy]==1:
      reachable=False
      break
    cx+=dx
    cy+=dy
  if reachable:
    print("Yes")
  else:
    print("No")